### ISSUE TITLE
Rails 4 compatibility

### ISSUE THREAD

**Issue by simonedamico** [samvincent/rqrcode-rails3#17]
I am wondering if this library is compatibile with rails 4 despite of the name.
Anyone is already using it in production?

**Comment by jalcine** [comment]
Easier way to find out is to _try it_. I'm going to do so over the next few days.

**Comment by ngottlieb** [comment]
I just upgraded an app to Rails 4.1-rc1 and have found so far that it continues to work with SVG format, but that either it or mini_magick seems to have broken and so none of the gif/jpeg/png formats are working. 

```
undefined method `size' for nil:NilClass
```

Ruby 2.0.0p353, rails 4.1.0.rc1. It actually worked fine on Rails 4.0.0.

Unfortunately don't have time to look into the problem myself right now so I'm just going to use SVG, but happy to help investigate sometime next week -- have either of you gotten anywhere with it?

**Comment by samvincent** [comment]
Do you have ImageMagick installed? I tested with Ruby 2.0 and it seems to work fine.

**Comment by ngottlieb** [comment]
See my edit -- it worked on the same machine w/ Ruby 2.0, Rails 4.0, but now that I've upgraded to Rails 4.1-rc1 it no longer works.

**Comment by astorrer** [comment]
I recently used this in rails 4.1.7, and both PNG and SVG work. I just installed rmagick, and used the mini magic gem.
